services:
  db:
    image: postgres:18
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=devsearchdb
      - POSTGRES_USER=devsearch
      - POSTGRES_PASSWORD=atulyajaiswal

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080